version: '3.8'

services:
  notes:
    build:
      context: .
    ports:
      - 8000:8000
      - 3000:3000
      - 9229:9229
    env_file: ./config/.env
    environment:
      - SERVER_PORT=$SERVER_PORT
      - DB_PATH=$DB_PATH
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
      - ./client/node_modules:/app/client/node_modules
    command: npm run dev
  mongo:
    image: mongo:5.0.6
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
volumes:
  mongodb:
  mongodb_config:
  node_modules:
  client-node_modules: